extends Resource
class_name words

# words class that can be refrenced from ANAYWHERE OOOO
var easy = [
'cool',
'radical',
'guns',
'dmc',
'gary',
'super',
'easy',
'cooler',
'2pac',
'60mph',
'dragonball',
'rose',
'tuesday',
'krakatoa',
'brown',
'sopranos',
'cpu',
'gpu',
'zoinks',
'jinkies',
'wahoo',
'bazinga',
'howdy',
'deez',
'doody',
'chimp',
'zumba',
'baby',
'frick',
'fricken',
'pizza',
'hackzors',
'hello',
'jimin',
'ham',
'hamble',
'hamtastic',
'oops',
'sike',
'dark souls',
'dark souls 2',
'sonic',
'tails',
'tales',
'cyberdrive',
'rachet and crack',
'crack',
'meth',
'dope',
'harold',
'knack',
'morbius',
'smb2',
'yo momma',
'kumar',
'chump',
'chumpette',
'pimpmobile',
'bite',
'shiny',
'daffodil',
'ass',
'mtn dew',
'doritos',
'baja blast']

var medium = [
'radicool',
'skater',
'kickflip',
'ice cube',
'metal gear',
'garys mod',
'ultimate',
'videogamedunkey',
'bababooey',
'legendairy',
'kaboom',
'medium',
'coolest',
'two pac',
'chilli dog',
'dr mundo',
'jumanji',
'pickleball',
'diarrhoea',
'baseballz',
'spaceballs',
'dragonball z',
'dragonball super',
'dragonball gt',
'krunky burger',
'dingleberry',
'cubevision',
'matrix reloaded',
'shazam',
'cowabungulus',
'la familia',
'ratatoullie',
'chimpette',
'chimpion',
'boss baby',
'cheeseburger',
'wild west',
'wee wee ca ca',
'sopranos poo',
'dr donezo',
'ham hock',
'hammaculate',
'silly sausage',
'dark souls 3',
'dark souls four',
'dark souls madden',
'madden souls',
'madden madness',
'madden nfl 94',
'fifa street',
'guatamala',
'minky mouse',
'jungle2jungle',
'donkey kong',
'copy that',
'copy that',
'copy that',
'dorans ring',
'grunka lunka',
'blackjack',
'hookers',
'cross the street',
'spirit blast',
'cuberella'
]

var hard = [
'cowabunga',
'32 bit processor',
'metal gear solid',
'hungry hippo',
'whooping cough',
'a w k w a r d',
'hard',
'killer crocks',
'kamp krusty',
'multiple packs shakur',
'aunt gemima',
'sons of the patriots',
'biggie smalls',
'smallsie biggs',
'roger da wabbit',
'naruto sucks lol',
'speculative execution',
'page fault handling',
'b tree rebalancing',
'service mesh telemetry',
'uzbeckystan',
'extreme zumba',
'can i get a bigger gun',
'keep my ham by my hide',
'i am out of ideas',
'mad madden men',
'john madden football 88',
'john madden football 92',
'john madden football 93',
'john madden football 94',
'madden nfl 95',
'madden nfl 96',
'madden nfl 97',
'madden football 64',
'madden nfl 98',
'madden nfl 99',
'madden nfl 00',
'madden nfl 01',
'madden nfl 02',
'madden nfl 03',
'madden nfl 04',
'madden nfl 05',
'madden nfl 06',
'madden nfl 07',
'madden nfl 08',
'madden nfl 09',
'madden nfl 10',
'madden nfl 11',
'madden nfl 12',
'jumanji nfl 14',
'unobtainium',
'municipal housing',
'jungle two jungle',
'level 4 naughty lister',
'super mario bruddas two',
'dorans new groove',
'who is yo daddy',
'knack 2',
'kill a man jar o',
'cubeiverse',
'in cube we trust'
]

var extreme = [
'birds of prey and the fantabulous parallelogram',
'japanese imported nintendo 64',
'device ran into a problem and needs to restart',
'ultra mega extreme zumba 9000',
'wicky wild west will smith',
'ham ham ham ham ham ham ham ham',
'john madden duo cd football 93',
'methamphetamines',
'merry christmas xbox',
'bowsers big bean burrito',
'star wars super bombad racing',
'harold n kumar white castle',
]
